server:
  port: 8080
  servlet:
    context-path: /aigc4chat

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:./file/project/db/aigc4chat-sqlite.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: ALWAYS
      continue-on-error: false
      data-locations: classpath*:sql/init.sql
      schema-locations: classpath*:sql/schema.sql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: pers.hll.aigc4chat.server.entity
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: pers.hll.aigc4chat.server.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
